[package]
name = "density_checker"
version = "0.1.0"
edition = "2021"
authors = ["Pacome Perrotin"]

[dependencies]
indicatif = { version = "0.17.7", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.8.0"
